//data
const { invoiceLabelSettingData} = require("../../data/updateInvoice/updateInvoiceLabelSettingData");

module.exports = {
    invoiceLabelSetting: {
      query: `
      mutation updateInvoiceLabelSetting($input:UpdateInvoiceLabelSettingInput!){
        updateInvoiceLabelSetting(input:$input){
          status
          data
          error
        }
      }`,
      input: ({
        isHidedeliverTo=false,
        labeldeliverTo=invoiceLabelSettingData.labeldeliverTo,
        isHidefulfillBy=false,
        labelfulfillBy=invoiceLabelSettingData.labelfulfillBy,
        isHideorderPayout=false,
        labelorderPayout=invoiceLabelSettingData.labelorderPayout,
        isHideorderTotal=false,
        labelorderTotal=invoiceLabelSettingData.labelorderTotal,
        isHideproduct=false,
        labelproduct=invoiceLabelSettingData.labelproduct,
        isHidepurchaseFrom=false,
        labelpurchaseFrom=invoiceLabelSettingData.labelpurchaseFrom,
        isHidequantity=false,
        labelquantity=invoiceLabelSettingData.labelquantity,
        isHidesellerCommission=false,
        labelsellerCommission=invoiceLabelSettingData.labelsellerCommission,
        isHideshippingPayout=false,
        labelshippingPayout=invoiceLabelSettingData.labelshippingPayout,
        isHidesku=false,
        labelsku=invoiceLabelSettingData.labelsku,
        isHidestatus=false,
        labelstatus=invoiceLabelSettingData.labelstatus,
        isHidesubtotal=false,
        labelsubtotal=invoiceLabelSettingData.labelsubtotal,
        isHidetax=false,
        labeltax=invoiceLabelSettingData.labeltax,
        isHidetotal=false,
        labeltotal=invoiceLabelSettingData.labeltotal,
        isHidetotalDeduction=false,
        labeltotalDeduction=invoiceLabelSettingData.labeltotalDeduction,
        isHidetotalDiscount=false,
        labeltotalDiscount=invoiceLabelSettingData.labeltotalDiscount,
        isHidetotalShipping=false,
        labeltotalShipping=invoiceLabelSettingData.labeltotalShipping,
        isHidetotalTax=false,
        labeltotalTax=invoiceLabelSettingData.labeltotalTax,
        isHidevendorAmount=false,
        labelvendorAmount=invoiceLabelSettingData.labelvendorAmount,
        isHidetotalVendorPayout=false,
        labeltotalVendorPayout=invoiceLabelSettingData.labeltotalVendorPayout,
        isHideshipping=false,
        labelshipping=invoiceLabelSettingData.labelshipping,
        isHidediscount=false,
        labeldiscount=invoiceLabelSettingData.labeldiscount,
        isHidePrice = false,
        labelPrice=invoiceLabelSettingData.labelPrice
        
      }) => ({
        input: {
          "price":{
              isHide:isHidePrice,
             label:labelPrice
          },
          "deliverTo":{
              isHide:isHidedeliverTo,
              label:labeldeliverTo
          },
          "fulfillBy":{
              isHide:isHidefulfillBy,
              label:labelfulfillBy
          },
          "orderPayout":{
              isHide:isHideorderPayout,
              label:labelorderPayout
          },
          "orderTotal":{
              isHide:isHideorderTotal,
              label:labelorderTotal
          },
          "product":{
              isHide:isHideproduct,
              label:labelproduct
          },
          "purchaseFrom":{
              isHide:isHidepurchaseFrom,
              label:labelpurchaseFrom
          },
          "quantity":{
              isHide:isHidequantity,
              label:labelquantity
          },
          "sellerCommission":{
              isHide:isHidesellerCommission,
              label:labelsellerCommission
          },
          "shippingPayout":{
              isHide:isHideshippingPayout,
              label:labelshippingPayout
          },
          "sku":{
              isHide:isHidesku,
              label:labelsku
          },
          "status":{
              isHide:isHidestatus,
              label:labelstatus
          },
          "subtotal":{
              isHide:isHidesubtotal,
              label:labelsubtotal
          },
          "tax":{
              isHide:isHidetax,
              label:labeltax
          },
          "total":{
              isHide:isHidetotal,
              label:labeltotal
          },
          "totalDeduction":{
              isHide:isHidetotalDeduction,
              label:labeltotalDeduction
          },
          "totalDiscount":{
              isHide:isHidetotalDiscount,
              label:labeltotalDiscount
          },
          "totalShipping":{
              isHide:isHidetotalShipping,
              label:labeltotalShipping
          },
          "totalTax":{
              isHide:isHidetotalTax,
              label:labeltotalTax
          },
          "vendorAmount":{
              isHide:isHidevendorAmount,
              label:labelvendorAmount
          },
          "totalVendorPayout":{
              isHide:isHidetotalVendorPayout,
              label:labeltotalVendorPayout
          },
          "shipping":{
              isHide:isHideshipping,
              label:labelshipping
          },
          "discount":{
              isHide:isHidediscount,
              label:labeldiscount
          }
        },
      }),
    },
  };
  